-- Insert ai_basics.md document with its content
-- This will be processed by the RAGAPI to generate embeddings

INSERT INTO documents (filename, content, file_hash, chunk_index)
VALUES (
    'ai_basics.md',
    'Artificial Intelligence Fundamentals

## Introduction

Artificial Intelligence (AI) represents one of the most transformative technologies of the 21st century. At its core, AI refers to the simulation of human intelligence in machines that are programmed to think and learn like humans.

## Key Concepts

### Machine Learning
Machine learning is a subset of AI that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. It focuses on the development of computer programs that can access data and use it to learn for themselves.

### Deep Learning
Deep learning is a specialized subset of machine learning that uses neural networks with multiple layers (hence "deep") to model and understand complex patterns in data. It has been particularly successful in areas like image recognition, natural language processing, and speech recognition.

### Neural Networks
Neural networks are computing systems vaguely inspired by the biological neural networks that constitute animal brains. They consist of interconnected nodes (neurons) that process information by responding to external inputs and relaying information between each node.

## Applications

AI has found applications in numerous fields:

- **Healthcare**: Diagnostic imaging, drug discovery, personalized medicine
- **Finance**: Fraud detection, algorithmic trading, risk assessment
- **Transportation**: Autonomous vehicles, traffic optimization, route planning
- **Technology**: Search engines, recommendation systems, virtual assistants

## Future Implications

The continued advancement of AI technology promises to revolutionize how we work, live, and interact with technology. However, it also raises important questions about ethics, employment, and the need for responsible development and deployment of AI systems.

## Conclusion

Understanding AI fundamentals is crucial for anyone looking to navigate the increasingly AI-driven world. As these technologies continue to evolve, staying informed about their capabilities and limitations becomes ever more important.

## Author
The author of the document is George',
    'manual_ai_basics_hash',
    0
);

-- Note: The embedding will be generated by the RAGAPI when it processes this document
-- This simulates what the embeddings generator should have done
